### ISSUE TITLE
Implement a system to help input Kanji

### ISSUE THREAD

**Issue by Ynscription** [Ynscription/MiharuScanHelper#10]
When Tesseract fails it's quite the pain to go to a different software to get the kanji that Tesseract didn't pick up. This may or may not be feasable:
* A kanji by radical input system
* A draw recognition input system

**Comment by usagi123** [comment]
Furthermore, adding other result with lower confidence values for users to select might be also a good idea ie something like this. 
![image](https://user-images.githubusercontent.com/26373261/73659419-cd4cfe00-46c8-11ea-8a96-1f38393fabb2.png)

I know this is a bad example but imagine if Tesseract return ocr-ed result but does not fit to the human eyes, by displaying others lower confidence value characters out, users can pick the kanji character manually and fit your goal in this issue.

**Comment by Ynscription** [comment]
Problem is, right now Miharu uses Tesseract externally. In order to do what you suggest Tesseract must be used as a library.
This was the original plan, but it turns out that binding Tesseract in c# is quite challenging, thus the easier solution was used.

I will do more research on this soonᵀᴹ because your suggestion is great.

**Comment by Ynscription** [comment]
Research has been done and all NuGet packages for Tesseract 4 are either abandoned or not properly setup, making it impossible to use Tesseract as a library until they are updated and fixed.

Thus this issue will become won't fix until Tesseract packages are updated.

**Comment by Ynscription** [comment]
This issue was solved in version 1.8.
