### ISSUE TITLE
Web Crawling for Translation Sources

### ISSUE THREAD

**Issue by Ynscription** [Ynscription/MiharuScanHelper#16]
After tinkering with the Yandex.Translate API it's clear that the free APIs can't compare to the web versions (except for Bing which seems to return the same quality of results through the API and the web app).

Adding new Translation Sources acquired through Web Crawling will be a valuable addition.

**Comment by usagi123** [comment]
This is just my thought after using the software for less than an hour so I might miss something. So, back to your enhancement problem. I am not sure how 3 translate services API return and the quality of free API compared to the paid one, not to consider the free quota but I am sure that you can query Google Translate and Yandex to translate with a simple modify to the URL. So if there is a quality difference between API and web translation, I think you should add a button that open the web translation version, similar to what you have done with jisho.

**Comment by Ynscription** [comment]
This whole problem was solved as of [last release](https://github.com/Ynscription/MiharuScanHelper/releases/tag/v1.5.1.b) with the reimplementation of web crawling.
