### ISSUE TITLE
Application crashes when trying to scan text

### ISSUE THREAD

**Issue by Desox7** [Ynscription/MiharuScanHelper#28]
I honestly don't know what's going on, Miharu opens perfectly, opens the files and all, but every time you click to scan... it just crashes.

Here's the log: 

```
!!!!![Exception]!!!!!<System.IO.FileNotFoundException>
  <Message>No se pudo encontrar el archivo 'D:\Miharu.v1.8.0\tmp.hocr'.</Message>
  <StackTrace>   en Miharu.Control.PageManager.AddTextEntry(DPIAwareRectangle rect)
   en Miharu.FrontEnd.Page.PageControl.PreviewIMG_MouseMove(Object sender, MouseEventArgs e)
   en System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   en System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   en System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   en System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   en System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   en System.Windows.Input.InputManager.ProcessStagingArea()
   en System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   en System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   en System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   en System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   en System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   en MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean&amp; handled)
   en MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   en System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   en System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   en System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   en MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   en MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG&amp; msg)
   en System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   en System.Windows.Application.RunDispatcher(Object ignore)
   en System.Windows.Application.RunInternal(Window window)
   en Miharu.App.Main(String[] args)</StackTrace>
  <Data>
    <System.Object />
  </Data>
</System.IO.FileNotFoundException>

```

I have noted no tmp.hocr is made, but a tmp.jpeg containing the selected text is. I had tesseract beforehand, will try updating it and see what happens.

**Comment by Desox7** [comment]
Yup, still not working.

Tried moving it to C:\ to test if it was that. It wasn't. Here's the log and not the crash dump:

```!!!!![Exception]!!!!!<System.IO.FileNotFoundException>
  <Message>No se pudo encontrar el archivo 'C:\Miharu.v1.8.0\tmp.hocr'.</Message>
  <StackTrace>   en System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   en System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   en System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   en System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   en System.IO.StreamReader..ctor(String path)
   en Miharu.BackEnd.Data.Text.ReadHOCR(String hocrPath)
   en Miharu.BackEnd.Data.Text.ParseText()
   en Miharu.BackEnd.Data.Text.get_ParsedText()
   en Miharu.FrontEnd.TextEntry.TextEntryListView..ctor(Text textEntry, PageManager pageManager)
   en Miharu.FrontEnd.TextEntry.TextEntryView.OnTextEntryAdded(Object sender, ListModificationEventArgs e)
   en Miharu.Control.PageManager.AddTextEntry(DPIAwareRectangle rect)</StackTrace>
</System.IO.FileNotFoundException>
```

**Comment by Desox7** [comment]
Okay, so obviously something was conflicting on my windows desktop, as creating an initial *.hocr was impossible. However, after trying to do through my laptop, the program worked, and after copying those files back to the desktop, Miharu suddenly works.

Evidently there was a conflict with Windows, I guess.

**Comment by Ynscription** [comment]
That is indeed extrange, what version of Tesseract are you running? 
You can check by running
`tesseract --version`

**Comment by Ynscription** [comment]
Ah, since you already have Tesseract installed I presume you don't have a jpn_vert trained data do you?

**Comment by Ynscription** [comment]
Try adding [this trained data set](https://github.com/tesseract-ocr/tessdata_best/blob/master/jpn_vert.traineddata) to your Tesseract installation, that should fix the issue.

Alternatively, in the settings menu you can set Miharu to use it's own distribution of Tesseract that should give you no problems.

**Comment by Desox7** [comment]
Sadly, not. It's not working with the Tesseract version I had or Miharu's distribution. It's like it is conflicting with Windows somehow.

If I grab the exact same folder with the exact same settings, put it on a flashdrive and use Miharu from my laptop, it works without a hitch. But on my desktop, it hangs, then crashes and leaves that log info. I'm not an expert on this, but from what I saw online, it seems to have to do with file permission errors, either because other program has it open, or due to permissions themselves.

I don't know if it helps, but... the only two differences between the Windows on my laptop and my desktop are:

I) I have multiple drives (four) on my desktop (Miharu didn't work in any), only one on my laptop. 

II)The username on my desktop computer has unicode characters (in this case í), while my laptop has another username. I know I've had lots of problems with programs due to it.

**Comment by Ynscription** [comment]
Try to run Tesseract from a terminal with the following options and share the results:
`tesseract [image] tmp -l jpn_vert --psm 5 hocr`

**Comment by Desox7** [comment]
Thanks for the clue, I'm glad to say that I've found a solution given the answer tesseract gave me.

Seems Windows decided to truncate the permissions of the downloaded trained data, so that was basically the isue. I reset the permissions, and just in case, rechecked tesseract to run as administrator under its properties, and suddenly, miharu began working! 

Thank you.
