### ISSUE TITLE
Papago support

### ISSUE THREAD

**Issue by nakichiam** [Ynscription/MiharuScanHelper#29]
Is it possible to implement papago? It is second to DeepL when it comes to translation.

**Comment by Ynscription** [comment]
Certainly, it might take a couple of days, though.

**Comment by Ynscription** [comment]
Added support on commit 6753180b5e0ca869eadbf004baf3f0e529a3686d
Available on release https://github.com/Ynscription/MiharuScanHelper/releases/tag/v1.8.3
